import numpy as np

from pathlib import Path

from astropy.io import fits

import matplotlib.pyplot as plt

from basic_calibration.combine import combine

plt.rcParams.update({
    "font.size": 12,
    "axes.titlesize": 28,
    "axes.labelsize": 18,
    "xtick.labelsize": 16,
    "ytick.labelsize": 16,
    "legend.fontsize": 16,
    "figure.titlesize": 28
})

plt.rcParams["figure.dpi"] = 200


def flat(flat_files, files, method='median',
         width=50, plot_response=False,
         fit_func='spline3', order=50,
         plot_fit=False,
         view_stats=True, correct=True,
         output_dir=None, overwrite=False):

    """
    This function creates a normalized master flat (response image) from
    a set of flat-field exposures.
    
    The response spectrum is estimated from the brightest region of the
    slit and used to remove the wavelength-dependent sensitivity pattern
    from the combined flat image.
    
    Optionally, the resulting master flat can be applied to a set of
    science images.

    Parameters
    ----------
    flat_files : list
        List of paths to the flat files to be combined
        for create the flat_master file.
        All images must have identical dimensions.
        
    files : list of str
        List of paths to the FITS files to be corrected
        by the flat_master.

    method : {'median', 'mean', 'min', 'max'}, optional
        Statistical estimator used to combine the flat images:

        - 'median' : Pixel-wise median (robust against outliers)
        - 'mean'   : Pixel-wise arithmetic mean
        - 'min'    : Pixel-wise minimum
        - 'max'    : Pixel-wise maximum

        Default is 'median'.

    width : int, optional
        Width (in pixels) of the spatial region centered on the brightest
        part of the slit used to estimate the response spectrum.
        Default is 50.

    plot_response : bool, optional
        If True, display the extracted one-dimensional response spectrum
        used to construct the master flat.
        Default is False.    

    view_stats : Boolean, optional
        If True, plot basic statistics (mean, median, std, etc.)
        of the flat_master.
        Default is True.

    correct : Boolean, optional
        If True, correct by the flat_master each file in files.
        Default is True.

    output_dir : str, optional
        Output directory where the flat corrected files must be saved.
        If None, a directory called stage2 is created and the files are 
        saved there.

    overwrite : Boolean, optional
        If True, existing output files are overwritten.

        If False, original files are never overwritten. The flat-corrected
        images are written to output_dir using the suffix "_f.fits".
        If a file with that name already exists, this is overwritten.
    
        Default is False.

    Returns
    -------
    None
        Creates a normalized master flat (response image) from the
        input flat-field exposures.
    
        Optionally applies the response correction to the images
        provided in 'files'.
    
        All outputs are written to disk.

    Notes
    -----
    - Flat files must have the same size.
    - Each file in files must have the same size as the generated
      master flat.
    - The detector dispersion axis is determined from the FITS keyword
      DISPAXIS.
    - A spatial profile is estimated near the center of the dispersion
      axis to identify the brightest region of the slit.
    - The response spectrum is extracted from this region using the
      median signal across a user-defined spatial width.
    - The master flat is generated by dividing the combined flat image
      by the extracted response spectrum.


    Raises
    ------
    ValueError
        If flat images do not share identical dimensions.
    
        If any image in 'files' does not match the dimensions of the
        master flat.
    
        If 'DISPAXIS' is missing from the FITS header or is not equal
        to 1 or 2.
    
        If 'method' is not one of
        {'median', 'mean', 'min', 'max'}.
    """

    # Check the path of output_dir
    output_dir = Path(output_dir) if output_dir is not None else Path(flat_files[0]).parent / "stage2"
    output_dir.mkdir(parents=True, exist_ok=True)

    ######################################
    # Create and open the flat_combined
    ######################################

    flat_path = output_dir / "flat_combined.fits"
    combine(flat_files, align = False, sigma = 3, method = method, result_img = str(flat_path))

    with fits.open(flat_path) as hdul:
        flat = hdul[0].data
        flat_hdr = hdul[0].header

    ######################################
    # Determine the dispersion and spatial axis
    ######################################

    # Determine dispersion axis
    disp_axis = flat_hdr.get('DISPAXIS', None)

    if disp_axis not in (1, 2):
        raise ValueError("DISPAXIS not defined or invalid in header")

    # Determine spatial axis
    spatial_axis = 0 if disp_axis == 1 else 1
    dispersion_axis = 1 if disp_axis == 1 else 0

    ######################################
    # Get the response in the dispersion-axis
    ######################################

    # Find the brightest pixs in the spatial axis
    mid_disp_pix = flat.shape[dispersion_axis] // 2
    disp_start = max(0, mid_disp_pix-5)
    disp_end   = min(flat.shape[dispersion_axis], mid_disp_pix+6)
    if dispersion_axis == 0:
        profile_region = flat[disp_start:disp_end, :]
        mid_spatial_data = np.nanmedian(profile_region, axis=dispersion_axis)
    else:
        profile_region = flat[:, disp_start:disp_end]
        mid_spatial_data = np.nanmedian(profile_region, axis=dispersion_axis)

    brightest_pix = np.nanargmax(mid_spatial_data)
    
    # Get the response of the flat_combined file
    start = max(0, brightest_pix - width//2)
    end   = min(flat.shape[spatial_axis], brightest_pix + width//2 + 1)

    if spatial_axis == 0:
        region = flat[start:end, :]
    else:
        region = flat[:, start:end]

    response = np.nanmedian(region, axis=spatial_axis)

    if plot_response:
        
        fig, ax = plt.subplots(figsize=(16, 8))
        ax.plot(response, lw = 2, color = 'blue', label = 'Response')
        ax.grid()
        ax.set_title('Response on dispersion axis')
        ax.set_xlabel('Pixels')
        ax.set_ylabel('Counts')
        ax.legend()
        plt.show()

    ######################################
    # Construct the flat_combined model image normalized
    ######################################

    if disp_axis == 2:
        norm = response[:, None]
    elif disp_axis == 1:
        norm = response[None, :]

    flat_response = flat / norm
    
    ######################################
    # Save the flat_response
    ###################################### 
    flat_response_hdr = flat_hdr.copy()

    flat_response_path = output_dir / "flat_master.fits"

    fits.PrimaryHDU(data=flat_response, header=flat_response_hdr).writeto(str(flat_response_path), overwrite=True)
    
    # Plot the statistics of flat_master.fits
    ######################################
    if view_stats:

        print("Master Flat Statistics")
        print("----------------------")
        print(f"Npix        : {flat_response.size}")
        print(f"Mean        : {np.nanmean(flat_response):.2f}")
        print(f"Median      : {np.nanmedian(flat_response):.2f}")
        print(f"Std         : {np.nanstd(flat_response):.5f}")
        print(f"Min         : {np.nanmin(flat_response):.5f}")
        print(f"Max         : {np.nanmax(flat_response):.5f}")

    ######################################
    # Correct each file using the flat_master
    ######################################
    if correct:
        print('Response correction applied to:')
    
        for f in files:
            with fits.open(f) as hdul:
                data = hdul[0].data.astype(float)
                hdr = hdul[0].header

            if data.shape != flat_response.shape:
                raise ValueError(
                    f"Image {f} has shape {data.shape}, "
                    f"but master flat has shape {flat_response.shape}.")

            data = data / flat_response

            hdr.add_history('--- Response correction ---')
            hdr.add_history('Response correction was made using')
            hdr.add_history(str(flat_response_path))

            if overwrite == True:
                out_file = f
            else:
                p = Path(f)
                out_file = output_dir / (p.stem + "_f" + p.suffix)

            fits.writeto(out_file, data, hdr, overwrite=overwrite)
            print(f"File : {out_file}")




####################################################################################################################################

def flat_bands(flat_files, files, method='median',
               width=50, view_stats=True, correct=True,
               output_dir=None, overwrite=False):

    """
    Create a normalized master flat (response image) from a set of
    flat-field exposures.
    
    The combined flat image is divided into spatial bands of fixed width.
    For each band, a representative response spectrum is computed from
    the median signal along the spatial direction. These spectra are then
    used to construct a two-dimensional response model that preserves
    large-scale variations of illumination along the slit.
    
    Optionally, the resulting master flat can be applied to a set of
    science images.

    Parameters
    ----------
    flat_files : list
        List of paths to the flat files to be combined
        for create the flat_master file.
        All images must have identical dimensions.
        
    files : list of str
        List of paths to the FITS files to be corrected
        by the flat_master.

    method : {'median', 'mean', 'min', 'max'}, optional
        Statistical estimator used to combine the flat images:

        - 'median' : Pixel-wise median (robust against outliers)
        - 'mean'   : Pixel-wise arithmetic mean
        - 'min'    : Pixel-wise minimum
        - 'max'    : Pixel-wise maximum

        Default is 'median'.

    width : int, optional
        Width (in pixels) of each spatial band used to estimate the
        response spectrum.
        The detector is divided into consecutive spatial intervals of
        this width, and a median response spectrum is computed for
        each interval independently.
        Default is 50.

    view_stats : Boolean, optional
        If True, plot basic statistics (mean, median, std, etc.)
        of the flat_master.
        Default is True.

    correct : Boolean, optional
        If True, correct by the flat_master each file in files.
        Default is True.

    output_dir : str, optional
        Output directory where the flat corrected files must be saved.
        If None, a directory called stage2 is created and the files are 
        saved there.

    overwrite : Boolean, optional
        If True, existing output files are overwritten.

        If False, original files are never overwritten. The flat-corrected
        images are written to output_dir using the suffix "_f.fits".
        If a file with that name already exists, this is overwritten.
    
        Default is False.

    Returns
    -------
    None
        Creates a normalized master flat (response image) from the
        input flat-field exposures.
    
        Optionally applies the response correction to the images
        provided in 'files'.
    
        All outputs are written to disk.

    Notes
    -----
    - Flat files must have the same size.
    - Each file in files must have the same size as the generated
      master flat.
    - The detector is divided into spatial bands of width 'width'.
    - A median response spectrum is computed independently for each
      spatial band.
    - A two-dimensional response model is generated by replicating
      each band response across its corresponding spatial interval.
    - The master flat is generated by dividing the combined flat image
      by the extracted response spectrum.


    Raises
    ------
    ValueError
        If flat images do not share identical dimensions.
    
        If any image in 'files' does not match the dimensions of the
        master flat.
    
        If 'DISPAXIS' is missing from the FITS header or is not equal
        to 1 or 2.
    
        If 'method' is not one of
        {'median', 'mean', 'min', 'max'}.
    """

    # Check the path of output_dir
    output_dir = Path(output_dir) if output_dir is not None else Path(flat_files[0]).parent / "stage2"
    output_dir.mkdir(parents=True, exist_ok=True)

    ######################################
    # Create and open the flat_combined
    ######################################

    flat_path = output_dir / "flat_combined.fits"
    combine(flat_files, align = False, sigma = 3, method = method, result_img = str(flat_path))

    with fits.open(flat_path) as hdul:
        flat = hdul[0].data
        flat_hdr = hdul[0].header

    ######################################
    # Determine the dispersion and spatial axis
    ######################################

    # Determine dispersion axis
    disp_axis = flat_hdr.get('DISPAXIS', None)

    if disp_axis not in (1, 2):
        raise ValueError("DISPAXIS not defined or invalid in header")

    # Determine spatial axis
    spatial_axis = 0 if disp_axis == 1 else 1
    dispersion_axis = 1 if disp_axis == 1 else 0

    ######################################
    # Get the response in the dispersion-axis
    ######################################

    # Spatial intervals
    spatial_intervals = list(np.arange(0, flat.shape[spatial_axis], width))
    if spatial_intervals[-1] != flat.shape[spatial_axis]:
        spatial_intervals.append(flat.shape[spatial_axis])

    # Find the median response for each interval
    flat_response = np.zeros_like(flat, dtype=float)
        
    for start, end in zip(spatial_intervals[:-1], spatial_intervals[1:]):
        if spatial_axis == 0:
            region = flat[start:end, :]
            response = np.nanmedian(region, axis=spatial_axis)
            flat_response[start:end, :] = response[None, :]
        else:
            region = flat[:, start:end]
            response = np.nanmedian(region,axis=spatial_axis)
            flat_response[:, start:end] = response[:, None]

    ######################################
    # Construct the flat_combined model image normalized
    ######################################

    flat_master = flat / flat_response
    
    ######################################
    # Save the flat_response
    ###################################### 
    flat_master_hdr = flat_hdr.copy()

    flat_master_path = output_dir / "flat_master.fits"

    fits.PrimaryHDU(data=flat_master, header=flat_master_hdr).writeto(str(flat_master_path), overwrite=True)
    
    # Plot the statistics of flat_master.fits
    ######################################
    if view_stats:

        print("Master Flat Statistics")
        print("----------------------")
        print(f"Npix        : {flat_master.size}")
        print(f"Mean        : {np.nanmean(flat_master):.2f}")
        print(f"Median      : {np.nanmedian(flat_master):.2f}")
        print(f"Std         : {np.nanstd(flat_master):.5f}")
        print(f"Min         : {np.nanmin(flat_master):.5f}")
        print(f"Max         : {np.nanmax(flat_master):.5f}")

    ######################################
    # Correct each file using the flat_master
    ######################################
    if correct:
        print('Response correction applied to:')
    
        for f in files:
            with fits.open(f) as hdul:
                data = hdul[0].data.astype(float)
                hdr = hdul[0].header

            if data.shape != flat_master.shape:
                raise ValueError(
                    f"Image {f} has shape {data.shape}, "
                    f"but master flat has shape {flat_master.shape}.")

            data = data / flat_master

            hdr.add_history('--- Response correction ---')
            hdr.add_history('Response correction was made using')
            hdr.add_history(str(flat_master_path))

            if overwrite == True:
                out_file = f
            else:
                p = Path(f)
                out_file = output_dir / (p.stem + "_f" + p.suffix)

            fits.writeto(out_file, data, hdr, overwrite=overwrite)
            print(f"File : {out_file}")




####################################################################################################################################

def flat_test(flat_files, files, method = 'median', 
         fit_func = 'spline3', order = 50,
         view_stats = True, correct = True,
         output_dir = None, overwrite = False):

    """
    This function is used to know the response of 
    the detector due to the sensibility of different
    wavelenghts and the illumination of the field, by
    creating a flat_master file.
    Optionally, can plot the statistics of the flat_master
    and also correct by this image a set of files.

    Parameters
    ----------
    flat_files : list
        List of paths to the flat files to be combined
        for create the flat_master file.
        All images must have identical dimensions.
        
    files : list of str
        List of paths to the FITS files to be corrected
        by the flat_master.

    method : {'median', 'mean', 'min', 'max'}, optional
        Statistical estimator used to combine the flat images:

        - 'median' : Pixel-wise median (robust against outliers)
        - 'mean'   : Pixel-wise arithmetic mean
        - 'min'    : Pixel-wise minimum
        - 'max'    : Pixel-wise maximum

        Default is 'median'.

    fit_func : {'spline1', 'spline3', 'legendre', 'chebyshev'}, optional
        Function to be used for fit the response of the detector along 
        the dispersion axis.

        Default is 'spline3'.

    order : int, optional
        Order of the fitting function or the number of inside knots for splines.

        Default is 50.

    view_stats : Boolean, optional
        If True, plot basic statistics (mean, median, std, etc.)
        of the flat_master.
        Default is True.

    correct : Boolean, optional
        If True, correct by the flat_master each file in files.
        Default is True.

    output_dir : str, optional
        Output directory where the flat corrected files must be saved.
        If None, a directory called stage1 is created and the files are 
        saved there.

    overwrite : Boolean, optional
        If True, existing output files are overwritten.

        If False, original files are never overwritten. The flat-corrected
        images are written to output_dir using the suffix "_f.fits".
        If a file with that name already exists, this is overwritten.
    
        Default is False.

    Returns
    -------
    None
        This function creates a master flat image from flat_files.
        Depending on the input parameters, it may:
    
        - Correct by the master flat a set of images in files
          (correct=True).
        - Overwrite existing files if overwrite=True.
    
        No objects are returned; all operations are performed on disk.

    Notes
    -----
    - Flat files must have the same size.
    - Each file in files must have the same size as the flat_master


    Raises
    ------
    ValueError
        If flat images do not share identical dimensions.
        If any image in 'files' does not match the flat_master dimensions.
        If 'method' is not one of {'median', 'mean', 'min', 'max'}.
        If 'fit_func' is not one of {'spline1', 'spline3', 'legendre', 'chebyshev'}
    """

    # Check the path of output_dir
    output_dir = Path(output_dir) if output_dir is not None else Path(flat_files[0]).parent / "stage1"
    output_dir.mkdir(parents=True, exist_ok=True)

    ######################################
    # Create and open the flat_main
    ######################################
    
    flat_path = output_dir / "flat_main.fits"
    combine(flat_files, align = False, sigma = 3, method = method, result_img = str(flat_path))

    with fits.open(flat_path) as hdul:
        flat = hdul[0].data
        flat_hdr = hdul[0].header

    ######################################
    # Determine the dispersion and spatial axis
    ######################################

    # Determine dispersion axis
    disp_axis = flat_hdr.get('DISPAXIS', None)

    if disp_axis not in (1, 2):
        raise ValueError("DISPAXIS not defined or invalid in header")

    # Determine spatial axis
    spatial_axis = 0 if disp_axis == 1 else 1

    ######################################
    # Fit the response in the dispersion-axis
    ######################################

    

    

    ######################################
    # Fit the response in the spatial-axis
    ######################################
    
    
    # Get the response
    center = flat.shape[spatial_axis] // 2
    
    lo = max(center - 10, 0)
    hi = min(center + 10 + 1, flat.shape[spatial_axis]) # The plus 1 is for not exclude hi index in the lists below
    
    if spatial_axis == 0:
        region = flat[lo:hi, :]
        response = np.nanmedian(region, axis=0)
    else:
        region = flat[:, lo:hi]
        response = np.nanmedian(region, axis=1)

    # Fit response 
    pixs = np.arange(len(response))

    if fit_func == "legendre":
        coeff = np.polynomial.legendre.legfit(pixs, response, order)
        fit = np.polynomial.legendre.legval(pixs, coeff)

    elif fit_func == "chebyshev":
        coeff = np.polynomial.chebyshev.chebfit(pixs, response, order)
        fit = np.polynomial.chebyshev.chebval(pixs, coeff)

    elif fit_func == "spline1":
        n_knots = order
        knots = np.linspace(pixs[0], pixs[-1], n_knots+2)[1:-1] # The plus 2 is for taking into account the extremes of the arange
        spline = LSQUnivariateSpline(pixs, response, knots, k=1)
        fit = spline(pixs)

    elif fit_func == "spline3":
        n_knots = order
        knots = np.linspace(pixs[0], pixs[-1], n_knots+2)[1:-1] # The plus 2 is for taking into account the extremes of the arange
        spline = LSQUnivariateSpline(pixs, response, knots, k=3)
        fit = spline(pixs)

    else:
        raise ValueError("Invalid fitting function")

    # Compute the rms
    residuals = response - fit
    rms = np.sqrt(np.nanmean(residuals**2))

    print(f"Fit made with {fit_func} function")
    print(f"Max response value: {np.nanmax(response)}")
    print(f"Min response value: {np.nanmin(response)}")
    print(f"RMS: {rms:.6f}")
    

    # Create a normalized flat
    flat_norm = np.ones_like(flat)
    
    if spatial_axis == 0:
        flat_norm[lo:hi, :] = flat[lo:hi, :] / fit
    else:
        flat_norm[:, lo:hi] = flat[:, lo:hi] / fit[:, None]
        
    flat_norm_hdr = flat_hdr.copy()
    
    flat_norm_hdr['FITFUNC'] = (fit_func, 'Function used to fit the response')
    if fit_func in ('spline1', 'spline3'):
        flat_norm_hdr['KNOTS'] = (order, 'Internal knots')
    else:
        flat_norm_hdr['ORDER'] = (order, 'Fit order')
    flat_norm_hdr['RMS'] = (round(rms,6), 'RMS value of the fit')

    flat_norm_path = output_dir / "flat_master.fits"

    fits.PrimaryHDU(data=flat_norm, header=flat_norm_hdr).writeto(
        str(flat_norm_path), overwrite=True
    )
    
    ######################################
    # Plot the statistics of flat_master.fits
    ######################################
    if view_stats:
        with fits.open(str(flat_norm_path)) as hdul:
            flat_master_data = hdul[0].data
    
        print("Master Flat Statistics")
        print("----------------------")
        print(f"Npix        : {flat_master_data.size}")
        print(f"Mean        : {np.nanmean(flat_master_data):.2f}")
        print(f"Median      : {np.nanmedian(flat_master_data):.2f}")
        print(f"RMS         : {rms:.5f}")
        print(f"Std         : {np.nanstd(flat_master_data):.5f}")
        print(f"Min         : {np.nanmin(flat_master_data):.5f}")
        print(f"Max         : {np.nanmax(flat_master_data):.5f}")

    ######################################
    # Correct each file using the flat_master
    ######################################
    if correct:
        print('Response correction applied to:')
    
        for f in files:
            with fits.open(f) as hdul:
                data = hdul[0].data.astype(float)
                hdr = hdul[0].header

            if data.shape != flat_norm.shape:
                raise ValueError(
                    f"Image {f} has shape {data.shape}, "
                    f"but master flat has shape {flat_norm.shape}.")

            data = data / flat_norm

            hdr.add_history('--- Response correction ---')
            hdr.add_history('Response correction have been made using')
            hdr.add_history(str(flat_norm_path))
            hdr.add_history(f'Fit function: {fit_func}')
            if fit_func in ('spline1', 'spline3'):
                hdr.add_history(f'Internal knots: {order}')
            else:
                hdr.add_history(f'Fit order: {order}')
            hdr.add_history(f'RMS: {rms:.6f}')

            if overwrite == True:
                out_file = f
            else:
                p = Path(f)
                out_file = output_dir / (p.stem + "_f" + p.suffix)

            fits.writeto(out_file, data, hdr, overwrite=overwrite)
            print(f"File : {out_file}")